let name = "Raju Khot";
let school = "S.H.V school";
let grade = 8;
let section = "B";
let rno = 24;
let sub1 = 76;
let sub2 = 86;
let sub3 = 56;
let sum = sub1+sub2+sub3;
console.log("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
console.log("Name: "+name, "|  Grade: "+grade);
console.log("Section: "+section,"|  School: "+school);
console.log("----------------------------------");
console.log("Subjects          ","Marks");
console.log("----------------------------------");
console.log("English            "+sub1);
console.log("Maths              "+sub2);
console.log("Science            "+sub3);
console.log("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
console.log("Total Marks        "+sum);